import sys, pandas as pd
sys.stdout.reconfigure(encoding='utf-8')

users  = pd.read_csv('users.csv')
rests  = pd.read_csv('restaurants.csv')
menu   = pd.read_csv('menu_items.csv')
orders = pd.read_csv('order_history.csv')
csao   = pd.read_csv('csao_interactions.csv')

print('=== DATASET SUMMARY ===')
print(f'Users:              {len(users):,}')
print(f'Restaurants:        {len(rests):,}')
print(f'Menu Items:         {len(menu):,}')
print(f'Orders:             {len(orders):,}')
print(f'CSAO Interactions:  {len(csao):,}')
print()
print(f'Acceptance rate:    {csao["was_added"].mean():.2%}')
print()
print('Acceptance by Hexagon Node:')
print(csao.groupby('hexagon_node')['was_added'].mean().sort_values(ascending=False).round(3).to_string())
print()
print('CSAO Columns:', list(csao.columns))
print()
print('Sample row:')
print(csao.head(2).to_string())
